image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install github-pages

pages:
  stage: deploy
  script:
    - github-pages build --destination public
  artifacts:
    paths:
      - public
